// @ts-check
import { defineConfig } from "astro/config";
import { readFileSync } from "node:fs";
import mdx from "@astrojs/mdx";
import react from "@astrojs/react";
import sitemap from "@astrojs/sitemap";
import vercel from "@astrojs/vercel";

// Canonical production URL. Override via the SITE env var when the real domain is set.
const SITE = process.env.SITE || "https://juma.org";

// 301 redirects from legacy WordPress URLs (generated by scripts/gen-redirects.mjs).
const redirects = JSON.parse(readFileSync(new URL("./src/redirects.json", import.meta.url), "utf8"));

export default defineConfig({
  site: SITE,
  // Static by default for top SEO/perf; API routes opt into server rendering via `export const prerender = false`.
  output: "static",
  adapter: vercel({ webAnalytics: { enabled: true } }),
  redirects,
  integrations: [mdx(), react(), sitemap()],
  // Tailwind v4 is wired via PostCSS (postcss.config.mjs) rather than the Vite
  // plugin, to stay compatible with Astro 6's Rolldown-based Vite.
  image: {
    // Allow optimizing images we reference from the legacy CDN during migration.
    domains: ["juma.org"],
  },
});
